name: Deploy DB Migrations (EC2)

on:
  push:
    branches:
      - main

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and run migrations
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/wilvault-db
            git pull origin main
            cd database/migration
            set -a; source ~/wilvault-db/.env; set +a
            goose up
